module.exports = {
    fetchUser: "FETCH_USER",
    fetchedUser: "FETCHED_USER",
    logoutUser: "LOGOUT_USER",
    loggedout: "LOGGED_OUT",
    fetchQuestions: "FETCH_QUESTIONS",
    fetchQuizzes: "FETCH_QUIZZES",
    addQuestion: "ADD_QUESTION",
    questionAdded: "QUESTION_ADDED",
    questionsFetched: "QUESTIONS_FETCHED",
    quizzesFetched: "QUIZZES_FETCHED",
    deleteQuestion: "DELETE_QUESTION",
    questionDeleted: "QUESTION_DELETED",
    editQuestion: "EDIT_QUESTION",
    questionEdited: "QUESTION_EDITED",
    createQuiz: 'CREATE_QUIZ',
    quizCreated:   'QUIZ_CREATED',
    editQuiz: 'EDIT_QUIZ',
    quizEdited: 'QUIZ_EDITED',
    quizDeleted: 'QUIZ_DELETED',
    deleteQuiz: 'DELETE_QUIZ',
    quizFormSubmit: 'QUIZ_FORM_SUBMIT',
    quizStarted:'QUIZ_STARTED',
    fetchCandidateQuestions: 'FETCH_CAND_QUESTIONS',
    candidateQuesFetched: 'CANDIDATE_QUES_FETCHED',
    submitResult: 'SUBMIT_RESULT',
    resultSubmitted:'RESULT_SUBMITTED'
};